/*
 * ucrypt_error.h
 */
#ifndef __UCRYPT_ERROR_H__
#define __UCRYPT_ERROR_H__
#include "ucrypt_common.h"
/*
 * following variables allows us to change standard program output behaviour 
 */
#define UCRYPT_STDOUT stdout
#define UCRYPT_STDERR stderr
#define UCRYPT_STDIN stdin
/*
 * set UCRYPT_DEBUG to TRUE or FALSE to enable debugging messages being sent to
 * stderr
 */
#define UCRYPT_DEBUG TRUE
#define UCRYPT_ERR_STRING_LEN 200
#define UCRYPT_OK 0

//standard error codes
typedef enum{UCRYPT_ERR_INVALID_ARGS=1,UCRYPT_ERR_INVALID_COMMAND,
			UCRYPT_ERR_PATH_LIMIT,
			UCRYPT_ERR_FILE_CREATE,UCRYPT_ERR_FILE_OPEN,
			UCRYPT_ERR_FILE_READ,UCRYPT_ERR_FILE_WRITE,
			UCRYPT_ERR_TTY,
			UCRYPT_ERR_IV_GEN,UCRYPT_ERR_IV_LOAD,
			UCRYPT_ERR_KEY_GEN,UCRYPT_ERR_INVALID_ALGO,
			UCRYPT_ERR_MEM,UCRYPT_ERR_INVALID_JOBQ,
			UCRYPT_ERR_HEADER_GEN,UCRYPT_ERR_HEADER_READ,
			UCRYPT_ERR_VERSION_INCOMPAT,UCRYPT_ERR_CRYPT,
			UCRYPT_ERR_DCRYPT,UCRYPT_ERR_ATTR_LOAD,
			UCRYPT_ERR_HMAC_ATTACH,UCRYPT_ERR_HMAC_VERIFY,
			UCRYPT_ERR_PASSWD_READ,UCRYPT_ERR_FRAME_READ,
			UCRYPT_ERR_FRAME_WRITE,
			UCRYPT_ERR_ATTR_INVALID_CODE,UCRYPT_ERR_ATTR_INVALID_LEN,
			UCRYPT_ERR_ATTR_INVALID_DATA,
			UCRYPT_ERR_LOG_INIT,UCRYPT_ERR_JOB_PROCESS,
			UCRYPT_ERR_GENERIC} error_codes_t;

void ucrypt_log_error();

#endif

